# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set([('creator', 'name')]),
        ),
    ]
