# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country_code',
            new_name='country_name',
        ),
    ]
